// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `Account.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


using _System = global::System;

#pragma warning disable 1591

namespace IceCompactId
{
}

namespace Kitchen
{
    namespace PocoInterfaces
    {
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1715")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1722")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1724")]
        [_System.Serializable]
        public partial class LoginInfo : _System.ICloneable
        {
            #region Slice data members

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
            public byte ret;

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
            public string token;

            #endregion

            partial void ice_initialize();

            #region Constructors

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
            public LoginInfo()
            {
                this.token = "";
                ice_initialize();
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
            public LoginInfo(byte ret, string token)
            {
                this.ret = ret;
                this.token = token;
                ice_initialize();
            }

            #endregion

            #region ICloneable members

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
            public object Clone()
            {
                return MemberwiseClone();
            }

            #endregion

            #region Object members

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
            public override int GetHashCode()
            {
                int h_ = 5381;
                IceInternal.HashUtil.hashAdd(ref h_, "::Kitchen::PocoInterfaces::LoginInfo");
                IceInternal.HashUtil.hashAdd(ref h_, ret);
                IceInternal.HashUtil.hashAdd(ref h_, token);
                return h_;
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
            public override bool Equals(object other)
            {
                if(object.ReferenceEquals(this, other))
                {
                    return true;
                }
                if(other == null)
                {
                    return false;
                }
                if(GetType() != other.GetType())
                {
                    return false;
                }
                LoginInfo o = (LoginInfo)other;
                if(!this.ret.Equals(o.ret))
                {
                    return false;
                }
                if(this.token == null)
                {
                    if(o.token != null)
                    {
                        return false;
                    }
                }
                else
                {
                    if(!this.token.Equals(o.token))
                    {
                        return false;
                    }
                }
                return true;
            }

            #endregion

            #region Comparison members

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
            public static bool operator==(LoginInfo lhs, LoginInfo rhs)
            {
                return Equals(lhs, rhs);
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
            public static bool operator!=(LoginInfo lhs, LoginInfo rhs)
            {
                return !Equals(lhs, rhs);
            }

            #endregion

            #region Marshaling support

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
            public void ice_writeMembers(Ice.OutputStream ostr)
            {
                ostr.writeByte(this.ret);
                ostr.writeString(this.token);
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
            public void ice_readMembers(Ice.InputStream istr)
            {
                this.ret = istr.readByte();
                this.token = istr.readString();
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
            public static void ice_write(Ice.OutputStream ostr, LoginInfo v)
            {
                if(v == null)
                {
                    _nullMarshalValue.ice_writeMembers(ostr);
                }
                else
                {
                    v.ice_writeMembers(ostr);
                }
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
            public static LoginInfo ice_read(Ice.InputStream istr)
            {
                var v = new LoginInfo();
                v.ice_readMembers(istr);
                return v;
            }

            private static readonly LoginInfo _nullMarshalValue = new LoginInfo();

            #endregion
        }

        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1715")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1722")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1724")]
        public partial interface IAccount : Ice.Object, IAccountOperations_
        {
        }
    }
}

namespace Kitchen
{
    namespace PocoInterfaces
    {
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
        public delegate void Callback_IAccount_LoginRequest(LoginInfo ret);
    }
}

namespace Kitchen
{
    namespace PocoInterfaces
    {
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
        public interface IAccountPrx : Ice.ObjectPrx
        {
            LoginInfo LoginRequest(string account, string pwd, Ice.OptionalContext context = new Ice.OptionalContext());

            _System.Threading.Tasks.Task<LoginInfo> LoginRequestAsync(string account, string pwd, Ice.OptionalContext context = new Ice.OptionalContext(), _System.IProgress<bool> progress = null, _System.Threading.CancellationToken cancel = new _System.Threading.CancellationToken());

            Ice.AsyncResult<Callback_IAccount_LoginRequest> begin_LoginRequest(string account, string pwd, Ice.OptionalContext context = new Ice.OptionalContext());

            Ice.AsyncResult begin_LoginRequest(string account, string pwd, Ice.AsyncCallback callback, object cookie);

            Ice.AsyncResult begin_LoginRequest(string account, string pwd, Ice.OptionalContext context, Ice.AsyncCallback callback, object cookie);

            LoginInfo end_LoginRequest(Ice.AsyncResult asyncResult);
        }
    }
}

namespace Kitchen
{
    namespace PocoInterfaces
    {
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
        public interface IAccountOperations_
        {
            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
            _System.Threading.Tasks.Task<LoginInfo> LoginRequestAsync(string account, string pwd, Ice.Current current = null);
        }
    }
}

namespace Kitchen
{
    namespace PocoInterfaces
    {
        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
        [_System.Serializable]
        public sealed class IAccountPrxHelper : Ice.ObjectPrxHelperBase, IAccountPrx
        {
            public IAccountPrxHelper()
            {
            }

            public IAccountPrxHelper(_System.Runtime.Serialization.SerializationInfo info, _System.Runtime.Serialization.StreamingContext context) : base(info, context)
            {
            }

            #region Synchronous operations

            public LoginInfo LoginRequest(string account, string pwd, Ice.OptionalContext context = new Ice.OptionalContext())
            {
                try
                {
                    return _iceI_LoginRequestAsync(account, pwd, context, null, _System.Threading.CancellationToken.None, true).Result;
                }
                catch(_System.AggregateException ex_)
                {
                    throw ex_.InnerException;
                }
            }

            #endregion

            #region Async Task operations

            public _System.Threading.Tasks.Task<LoginInfo> LoginRequestAsync(string account, string pwd, Ice.OptionalContext context = new Ice.OptionalContext(), _System.IProgress<bool> progress = null, _System.Threading.CancellationToken cancel = new _System.Threading.CancellationToken())
            {
                return _iceI_LoginRequestAsync(account, pwd, context, progress, cancel, false);
            }

            private _System.Threading.Tasks.Task<LoginInfo> _iceI_LoginRequestAsync(string iceP_account, string iceP_pwd, Ice.OptionalContext context, _System.IProgress<bool> progress, _System.Threading.CancellationToken cancel, bool synchronous)
            {
                iceCheckTwowayOnly(_LoginRequest_name);
                var completed = new IceInternal.OperationTaskCompletionCallback<LoginInfo>(progress, cancel);
                _iceI_LoginRequest(iceP_account, iceP_pwd, context, synchronous, completed);
                return completed.Task;
            }

            private const string _LoginRequest_name = "LoginRequest";

            private void _iceI_LoginRequest(string iceP_account, string iceP_pwd, _System.Collections.Generic.Dictionary<string, string> context, bool synchronous, IceInternal.OutgoingAsyncCompletionCallback completed)
            {
                var outAsync = getOutgoingAsync<LoginInfo>(completed);
                outAsync.invoke(
                    _LoginRequest_name,
                    Ice.OperationMode.Normal,
                    Ice.FormatType.DefaultFormat,
                    context,
                    synchronous,
                    write: (Ice.OutputStream ostr) =>
                    {
                        ostr.writeString(iceP_account);
                        ostr.writeString(iceP_pwd);
                    },
                    read: (Ice.InputStream istr) =>
                    {
                        LoginInfo ret = null;
                        ret = LoginInfo.ice_read(istr);
                        return ret;
                    });
            }

            #endregion

            #region Asynchronous operations

            public Ice.AsyncResult<Callback_IAccount_LoginRequest> begin_LoginRequest(string account, string pwd, Ice.OptionalContext context = new Ice.OptionalContext())
            {
                return begin_LoginRequest(account, pwd, context, null, null, false);
            }

            public Ice.AsyncResult begin_LoginRequest(string account, string pwd, Ice.AsyncCallback callback, object cookie)
            {
                return begin_LoginRequest(account, pwd, new Ice.OptionalContext(), callback, cookie, false);
            }

            public Ice.AsyncResult begin_LoginRequest(string account, string pwd, Ice.OptionalContext context, Ice.AsyncCallback callback, object cookie)
            {
                return begin_LoginRequest(account, pwd, context, callback, cookie, false);
            }

            public LoginInfo end_LoginRequest(Ice.AsyncResult asyncResult)
            {
                var resultI_ = IceInternal.AsyncResultI.check(asyncResult, this, _LoginRequest_name);
                var outgoing_ = (IceInternal.OutgoingAsyncT<LoginInfo>)resultI_.OutgoingAsync;
                return outgoing_.getResult(resultI_.wait());
            }

            private Ice.AsyncResult<Callback_IAccount_LoginRequest> begin_LoginRequest(string iceP_account, string iceP_pwd, _System.Collections.Generic.Dictionary<string, string> context, Ice.AsyncCallback completedCallback, object cookie, bool synchronous)
            {
                iceCheckAsyncTwowayOnly(_LoginRequest_name);
                var completed = new IceInternal.OperationAsyncResultCompletionCallback<Callback_IAccount_LoginRequest, LoginInfo>(
                    (Callback_IAccount_LoginRequest cb, LoginInfo ret) =>
                    {
                        if(cb != null)
                        {
                            cb.Invoke(ret);
                        }
                    },
                    this, _LoginRequest_name, cookie, completedCallback);
                _iceI_LoginRequest(iceP_account, iceP_pwd, context, synchronous, completed);
                return completed;
            }

            #endregion

            #region Checked and unchecked cast operations

            public static IAccountPrx checkedCast(Ice.ObjectPrx b)
            {
                if(b == null)
                {
                    return null;
                }
                IAccountPrx r = b as IAccountPrx;
                if((r == null) && b.ice_isA(ice_staticId()))
                {
                    IAccountPrxHelper h = new IAccountPrxHelper();
                    h.iceCopyFrom(b);
                    r = h;
                }
                return r;
            }

            public static IAccountPrx checkedCast(Ice.ObjectPrx b, _System.Collections.Generic.Dictionary<string, string> ctx)
            {
                if(b == null)
                {
                    return null;
                }
                IAccountPrx r = b as IAccountPrx;
                if((r == null) && b.ice_isA(ice_staticId(), ctx))
                {
                    IAccountPrxHelper h = new IAccountPrxHelper();
                    h.iceCopyFrom(b);
                    r = h;
                }
                return r;
            }

            public static IAccountPrx checkedCast(Ice.ObjectPrx b, string f)
            {
                if(b == null)
                {
                    return null;
                }
                Ice.ObjectPrx bb = b.ice_facet(f);
                try
                {
                    if(bb.ice_isA(ice_staticId()))
                    {
                        IAccountPrxHelper h = new IAccountPrxHelper();
                        h.iceCopyFrom(bb);
                        return h;
                    }
                }
                catch(Ice.FacetNotExistException)
                {
                }
                return null;
            }

            public static IAccountPrx checkedCast(Ice.ObjectPrx b, string f, _System.Collections.Generic.Dictionary<string, string> ctx)
            {
                if(b == null)
                {
                    return null;
                }
                Ice.ObjectPrx bb = b.ice_facet(f);
                try
                {
                    if(bb.ice_isA(ice_staticId(), ctx))
                    {
                        IAccountPrxHelper h = new IAccountPrxHelper();
                        h.iceCopyFrom(bb);
                        return h;
                    }
                }
                catch(Ice.FacetNotExistException)
                {
                }
                return null;
            }

            public static IAccountPrx uncheckedCast(Ice.ObjectPrx b)
            {
                if(b == null)
                {
                    return null;
                }
                IAccountPrx r = b as IAccountPrx;
                if(r == null)
                {
                    IAccountPrxHelper h = new IAccountPrxHelper();
                    h.iceCopyFrom(b);
                    r = h;
                }
                return r;
            }

            public static IAccountPrx uncheckedCast(Ice.ObjectPrx b, string f)
            {
                if(b == null)
                {
                    return null;
                }
                Ice.ObjectPrx bb = b.ice_facet(f);
                IAccountPrxHelper h = new IAccountPrxHelper();
                h.iceCopyFrom(bb);
                return h;
            }

            private static readonly string[] _ids =
            {
                "::Ice::Object",
                "::Kitchen::PocoInterfaces::IAccount"
            };

            public static string ice_staticId()
            {
                return _ids[1];
            }

            #endregion

            #region Marshaling support

            public static void write(Ice.OutputStream ostr, IAccountPrx v)
            {
                ostr.writeProxy(v);
            }

            public static IAccountPrx read(Ice.InputStream istr)
            {
                Ice.ObjectPrx proxy = istr.readProxy();
                if(proxy != null)
                {
                    IAccountPrxHelper result = new IAccountPrxHelper();
                    result.iceCopyFrom(proxy);
                    return result;
                }
                return null;
            }

            #endregion
        }
    }
}

namespace Kitchen
{
    namespace PocoInterfaces
    {
        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
        public abstract class IAccountDisp_ : Ice.ObjectImpl, IAccount
        {
            #region Slice operations

            public abstract _System.Threading.Tasks.Task<LoginInfo> LoginRequestAsync(string account, string pwd, Ice.Current current = null);

            #endregion

            #region Slice type-related members

            private static readonly string[] _ids =
            {
                "::Ice::Object",
                "::Kitchen::PocoInterfaces::IAccount"
            };

            public override bool ice_isA(string s, Ice.Current current = null)
            {
                return _System.Array.BinarySearch(_ids, s, IceUtilInternal.StringUtil.OrdinalStringComparer) >= 0;
            }

            public override string[] ice_ids(Ice.Current current = null)
            {
                return _ids;
            }

            public override string ice_id(Ice.Current current = null)
            {
                return _ids[1];
            }

            public static new string ice_staticId()
            {
                return _ids[1];
            }

            #endregion

            #region Operation dispatch

            [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
            public static _System.Threading.Tasks.Task<Ice.OutputStream>
            iceD_LoginRequest(IAccount obj, IceInternal.Incoming inS, Ice.Current current)
            {
                Ice.ObjectImpl.iceCheckMode(Ice.OperationMode.Normal, current.mode);
                var istr = inS.startReadParams();
                string iceP_account;
                string iceP_pwd;
                iceP_account = istr.readString();
                iceP_pwd = istr.readString();
                inS.endReadParams();
                return inS.setResultTask<LoginInfo>(obj.LoginRequestAsync(iceP_account, iceP_pwd, current),
                    (ostr, ret) =>
                    {
                        LoginInfo.ice_write(ostr, ret);
                    });
            }

            private static readonly string[] _all =
            {
                "LoginRequest",
                "ice_id",
                "ice_ids",
                "ice_isA",
                "ice_ping"
            };

            public override _System.Threading.Tasks.Task<Ice.OutputStream>
            iceDispatch(IceInternal.Incoming inS, Ice.Current current)
            {
                int pos = _System.Array.BinarySearch(_all, current.operation, IceUtilInternal.StringUtil.OrdinalStringComparer);
                if(pos < 0)
                {
                    throw new Ice.OperationNotExistException(current.id, current.facet, current.operation);
                }

                switch(pos)
                {
                    case 0:
                    {
                        return iceD_LoginRequest(this, inS, current);
                    }
                    case 1:
                    {
                        return Ice.ObjectImpl.iceD_ice_id(this, inS, current);
                    }
                    case 2:
                    {
                        return Ice.ObjectImpl.iceD_ice_ids(this, inS, current);
                    }
                    case 3:
                    {
                        return Ice.ObjectImpl.iceD_ice_isA(this, inS, current);
                    }
                    case 4:
                    {
                        return Ice.ObjectImpl.iceD_ice_ping(this, inS, current);
                    }
                }

                _System.Diagnostics.Debug.Assert(false);
                throw new Ice.OperationNotExistException(current.id, current.facet, current.operation);
            }

            #endregion
        }
    }
}
